import pygame
from constants import MEDIUM_FONT, SCREEN_NAMES, HIGH_SCORES_CONSTANTS
from utils import render_font, Ranking, Screen


class HighScores(Screen):
    '''
    Defines the high scores screen. Inherits screen methods from a parent
    class. Every frame of this screen is generated by running the function
    render_frame once.
    '''

    def __init__(self, name=''):
        '''
        Initializes parent class attributes, creates a Ranking
        object to deal with the high scores textfile, and creates
        two parallel lists to store the current high scores.

        Args:
            name (string): name of the player, optional
        '''
        super().__init__(name)

        self.ranking = Ranking('high_scores.txt')

        self.names = []
        self.scores = []

        score = self.ranking.get_players()

        for name in self.ranking.get_leaderboard()[:10]:
            self.names.append(
                render_font(name, font=MEDIUM_FONT, color=[0, 0, 255])
            )

            self.scores.append(
                render_font(str(score[name]),
                            font=MEDIUM_FONT, color=[0, 0, 255])
            )

    def render_frame(self):
        '''Renders one frame of the high scores screen on a pygame display'''
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                self.stop_running()

            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_q:
                    self.set_next_screen(SCREEN_NAMES[0])
                    self.stop_running()

        self.screen.fill([255, 184, 122])

        self.screen.blit(HIGH_SCORES_CONSTANTS['TITLE'], [10, 10])

        self.screen.blit(HIGH_SCORES_CONSTANTS['SUBTITLE'], [10, 50])

        for i in range(10):  # Renders each high score with a 25px margin
            self.screen.blit(self.names[i], [180, 25 * i + 90])
            self.screen.blit(self.scores[i], [360, 25 * i + 90])

        self.screen.blit(HIGH_SCORES_CONSTANTS['BACK'], [180, 360])

        pygame.display.update()
